### ISSUE TITLE
Is this working?

### ISSUE THREAD

**Issue by heynemann** [dhardy92/thumbor_riak#1]
I'd love to include it in the wiki! :)

**Comment by dhardy92** [comment]
Not tested for a while but it used to :)

Maybe Thumbor should provide agnostic module tests suite, that could be passed against any foreign module (loader, storage, engine,...) and follow Thumbor versions requisits so that older module can be confront to newer thumbor :)

**Comment by heynemann** [comment]
That's a great idea ;) Can you help us get it started?

Bernardo Heynemann
Developer @ globo.com

**Comment by dhardy92** [comment]
According to travis https://travis-ci.org/dhardy92/thumbor_riak/jobs/12275378 code still pass test with coverage of 100%

BUT if new feature of thumbor need more method it is not covered.

**Comment by dhardy92** [comment]
that is where python lack of some java interface notion

**Comment by heynemann** [comment]
Cool, do you want to add it to thumbor wiki of plugins?

Cheers,

Bernardo Heynemann
Developer @ globo.com

**Comment by dhardy92** [comment]
Done :)
