### ISSUE TITLE
riak vs s3 aws

### ISSUE THREAD

**Issue by danielmotaleite** [dhardy92/thumbor_riak#2]
Hi

As Riak support S3 API, how this compares against it? Faster? more features?
If all is the mostly the same, probably the s3 API is better, as is being maintained and it more flexible (easy to switch between aws and local riak just by changing the endpoing)

**Comment by dhardy92** [comment]
actually this plugin is not maintained any more for a very long time. I do not use it any more.
I moved to aws s3 storage since and the plugin from thumbor_community.
You are probably right about this.
